hydra:
  run:
    dir: .
  output_subdir:
  searchpath: # Only <exp_dir> in these paths are discoverable
    - pkg://configs

defaults:
  - scenarios: handpicked_100
  - risk: bound
  - hypothesis_generator: noisy
  - nuplan: default
  - results: default

main:
  verbose: False
simulation:
  simulation_history_buffer_duration: 2.0
  max_duration: null
  reactive_agents: True
hj_reachability:
  lut_table: "models/hj/hj_reachability.pkl"
  scene_radius: 100.0
trajectron:
  dt: 0.5
  model: "models/trajectron"
  subsample_ratio: 0.1
  num_samples: 1000
  scene_radius: 100.0
planner:
  IDMPlanner:
    target_velocity: 10
    min_gap_to_lead_agent: 0.5
    headway_time: 1.5
    accel_max: 1.0
    decel_max: 2.0
    planned_trajectory_samples: 10
    planned_trajectory_sample_interval: 0.2
    occupancy_map_radius: 20
  PredictionRiskPlanner:
    verbose: False
